---
apiVersion: batch/v1
kind: Job
metadata:
  name: chaincodeinstall
spec:
  backoffLimit: 1
  template:
    metadata:
      name: chaincodeinstall
    spec:
      restartPolicy: "Never"
      volumes:
      - name: sharedvolume
        persistentVolumeClaim:
          claimName: common-pvc
      containers:
      - name: chaincodeinstall1
        image: hyperledger/fabric-tools:1.3.0
        imagePullPolicy: Always
        command: ["sh", "-c", "echo $GOPATH ;mkdir -p $GOPATH/src/github.com/alcarria; cp -r /shared/artifacts/chaincode/data-marketplace-chaincode $GOPATH/src/github.com/alcarria/; ls $GOPATH/src/github.com/alcarria; peer chaincode install -n ${CHAINCODE_NAME} -v ${CHAINCODE_VERSION} -p github.com/alcarria/data-marketplace-chaincode/"]
        env:
        - name: CHAINCODE_NAME
          value: "dmp"
        - name: CHAINCODE_VERSION
          value: $VERSION
        - name: FABRIC_CFG_PATH
          value: /etc/hyperledger/fabric
        - name: CORE_PEER_MSPCONFIGPATH
          value: /shared/crypto-config/peerOrganizations/org1.example.com/users/Admin@org1.example.com/msp
        - name: CORE_PEER_LOCALMSPID
          value: Org1MSP
        - name: CORE_PEER_ADDRESS
          value: blockchain-org1peer1:30110
        - name: GODEBUG
          value: "netdns=go"
        volumeMounts:
        - mountPath: /shared
          name: sharedvolume

      - name: chaincodeinstall2
        image: hyperledger/fabric-tools:1.3.0
        imagePullPolicy: Always
        command: ["sh", "-c", "echo $GOPATH; mkdir -p $GOPATH/src/github.com/alcarria; cp -r /shared/artifacts/chaincode/data-marketplace-chaincode $GOPATH/src/github.com/alcarria; ls $GOPATH/src/github.com/alcarria; peer chaincode install -n ${CHAINCODE_NAME} -v ${CHAINCODE_VERSION} -p github.com/alcarria/data-marketplace-chaincode/"]
        env:
        - name: CHAINCODE_NAME
          value: "dmp"
        - name: CHAINCODE_VERSION
          value: $VERSION
        - name: FABRIC_CFG_PATH
          value: /etc/hyperledger/fabric
        - name: CORE_PEER_MSPCONFIGPATH
          value: /shared/crypto-config/peerOrganizations/org2.example.com/users/Admin@org2.example.com/msp
        - name: CORE_PEER_LOCALMSPID
          value: Org2MSP
        - name: CORE_PEER_ADDRESS
          value: blockchain-org2peer1:30210
        - name: GODEBUG
          value: "netdns=go"
        volumeMounts:
        - mountPath: /shared
          name: sharedvolume
